services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: skinx
      POSTGRES_PASSWORD: skinxpass
      POSTGRES_DB: skinxdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
